### PR TITLE
Create indices automatically - essential for IaaC approach

### PR DESCRIPTION
**Pull request by ChristophShyper**

### CODE REVIEW

**Comment by beezz** [comment]
Hi @Krzysztof-Szyper-Epam , thanks for your contribution!

I'm not a big fan of doing this by default and on each run of the function. Would you mind putting it behind environmental variable condition?

**Comment by ChristophShyper** [comment]
Operation is fairly quick. But of course putting some env condition is also a good idea. Whatever you think is better. 
Just to make it work, e.g. when one terminates/creates whole dev/test infra often.

**Comment by ChristophShyper** [comment]
Buy the way, can you add license information to your repo? I noticed that it's missing.

**Comment by beezz** [comment]
@Krzysztof-Szyper-Epam I added license and also the index creation, documented in README. Thanks for your addition!

**Comment by ChristophShyper** [comment]
Thank you very much :)

**Pull request merged**
